import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserIcon from "./components/UserIcon"; // added import for the user button

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header with top-right button */}
        <header className="flex justify-between items-center px-6 py-3 border-b border-gray-300">
          <h1>Chatbot App</h1>
          <UserIcon />
        </header>

        {/* Main content */}
        <main>{children}</main>
      </body>
    </html>
  );
}
